name: On Push Run

on: push

env:
  DEVOPS_DIR: devops

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: AlanJumeaucourt/tca-net
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: Install package
      run: pip install -r ${{ env.DEVOPS_DIR }}/requirement.txt
      shell: sh

    - name: Hello World
      run: python ${{ env.DEVOPS_DIR }}/crawler.py
      shell: sh
