name: On Push Run

on: push

env:
  DEVOPS_DIR: devops

jobs:
  scrapper:
    name: Run the scrapper
    runs-on: ubuntu-latest
    steps:
      - name: Check-out devops repository
        uses: actions/checkout@v2
        with:
          repository: AlanJumeaucourt/tca-net
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.DEVOPS_DIR }}

      - name: Install package
        run: pip install -r ${{ env.DEVOPS_DIR }}/requirement.txt
        shell: sh

      - name: Make .env file base on secrets
        env:
          AuthToken: ${{ secrets.AuthToken }}
          DiscordToken: ${{ secrets.DiscordToken }}
        run: |
          touch .env
          echo AuthToken=${{ secrets.AuthToken }} >> .env
          echo DiscordToken=${{ secrets.DiscordToken }} >> .env
          cat .env
        shell: sh

      - name: Launch crawler.py to scrap the tc-net
        run: python3 ${{ env.DEVOPS_DIR }}/crawler.py
        shell: sh

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ env.DEVOPS_DIR }}/data.json
  
      - name: ls devops
        run: ls ${{ env.DEVOPS_DIR }}
        shell: sh

      - name: ls
        run: ls ${{ env.DEVOPS_DIR }}
        shell: sh   

  discordNotif:
    needs: scrapper
    name: discordNotif
    runs-on: ubuntu-latest
    steps:
      - name: Check-out devops repository
        uses: actions/checkout@v2
        with:
          repository: AlanJumeaucourt/tca-net
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.DEVOPS_DIR }}

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ${{ env.DEVOPS_DIR }}/data.json

      - name: Install package
        run: pip install -r ${{ env.DEVOPS_DIR }}/requirement.txt
        shell: sh

      - name: Make .env file base on secrets
        env:
          channelId: ${{ secrets.channelId }}
          DiscordToken: ${{ secrets.DiscordToken }}
        run: |
          touch .env
          echo channelId=${{ secrets.channelId }} >> .env
          echo DiscordToken=${{ secrets.DiscordToken }} >> .env
          cat .env
        shell: sh

      - name: Launch discordBot.py to send notif to test server
        run: python3 ${{ env.DEVOPS_DIR }}/discordBot.py
        shell: sh
